name: Test Workflow
on:
  workflow_dispatch
jobs:
  Test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: parasoft/parasoft-coverage-action@jason_cicd961&&cicd983
        with:
          report: "**/*.xml"
      - uses: actions/upload-artifact@v3
        with:
          name: coberturaReport
          path: reports/unit/coverage-cobertura.xml
